apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }} 
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.container.port }}